MAX_SERVERS = 3
MAX_CLIENTS_PER_SERVER = 10
SERVER_NAMES = ["Server_A", "Server_B", "Server_C"]

# Network (optional if you use sockets later)
DEFAULT_PORT = 8080
HOST = "localhost"

# Client Settings
MAX_CLIENTS = 1000
CLIENT_WAITING_TIME_MINUTES = 5
MAX_SESSION_DURATION_MINUTES = 30  # Optional if you want timeouts

# Rating Scale
RATING_MIN = 1
RATING_MAX = 5
DEFAULT_RATING = 3

# Simulation
SIMULATION_CLIENTS = 1000
SIMULATION_DURATION_MINUTES = 15
LOAD_TEST_RAMP_UP_SECONDS = 5
LOAD_TEST_STEADY_STATE_SECONDS = 10

# Paths
DATABASE_PATH = "data/server_metrics.db"
SESSION_DATA_PATH = "data/session_data.json"
ARCHIVE_PATH = "archive.txt"

# Threading / Forking
MAX_THREADS = 50
THREAD_POOL_SIZE = 10
FORK_PROCESS_LIMIT = 10

# Logging Buffering
BUFFER_SIZE = 10
FLUSH_INTERVAL_SECONDS = 2
MAX_QUEUE_SIZE = 100
LOG_ROTATION_SIZE_MB = 5

# Performance Thresholds
METRICS_UPDATE_INTERVAL_SECONDS = 10
CPU_THRESHOLD_PERCENT = 85
MEMORY_THRESHOLD_PERCENT = 90
RESPONSE_TIME_THRESHOLD_MS = 500

# Concurrency Mode
DEFAULT_CONCURRENCY_METHOD = "threading"
CONCURRENCY_ITERATIVE = "iterative"
CONCURRENCY_THREADING = "threading"
CONCURRENCY_FORKING = "forking"
